name: Backend CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

permissions:
  contents: write

jobs:
  # ===================================================
  # 1) LINT — Static code style checks (Checkstyle)
  # ===================================================
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Checkstyle
        run: mvn -B checkstyle:check || true
        # `|| true` → does not break pipeline but shows warnings

  # ===================================================
  # 2) SECURITY SCAN — CodeQL + Trivy Vulnerability Scan
  # ===================================================
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- CodeQL Security Scan ----
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # ---- Docker Image Build (required for Trivy) ----
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: backend:latest

      # ---- Trivy Image Scan ----
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      # ---- Trivy Misconfiguration Scan ----
      - name: Trivy Dockerfile scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          format: table
          exit-code: 1

  # ===================================================
  # 3) TEST — Unit & Integration Tests
  # ===================================================
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Maven tests
        run: mvn -B test

  # ===================================================
  # 4) BUILD — Package JAR + Build Docker Image
  # ===================================================
  build:
    needs: [lint, security-scan, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies and package
        run: mvn -B -DskipTests package

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: backend:latest

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: target/*.jar

  # ===================================================
  # 5) RELEASE — Auto-create GitHub Release on PR
  # ===================================================
  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # auto available

    steps:
      - uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar

      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        with:
          title: Backend Build ${{ github.sha }}
          tag: backend-dev-${{ github.sha }}
          prerelease: true
